spring.application.name=examen_3
spring.datasource.url=jdbc:mysql://mysql-3ad0f86-practica-2.h.aivencloud.com:16696/examen_3?sslMode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_7y97vG9KINBPkMPUxEB
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect